spring.application.name=hotel-service

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
spring.kafka.consumer.group-id=hotel-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# JSON deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=com.challenge.hotel.infrastructure.kafka.model
spring.kafka.consumer.properties.spring.json.value.default.type=com.challenge.hotel.infrastructure.kafka.model.SearchEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hotel}
spring.datasource.username=${DB_USERNAME:hotel}
spring.datasource.password=${DB_PASSWORD:hotel}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true